import Link from "next/link";
import { Nanum_Pen_Script } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

export const nanumPen = Nanum_Pen_Script({
  variable: "--font-pen",
  weight: "400",
  subsets: ["latin"],
});

const doldam = localFont({
  variable: "--font-doldam",
  src: [
    {
      path: "../assets/fonts/doldam.woff2",
    },
    {
      path: "../assets/fonts/doldam.woff",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nanumPen.variable} ${doldam.variable}`}>
        <nav>
          <ul>
            <li className="font-pen">
              <Link href="/login">/login</Link>
            </li>
            <li>
              <Link href="/register">/register</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
