import Link from "next/link";
import "./globals.css";
export const metadata = {
  default: "Next.JS | hyeju",
  template: "%s | hyeju",
  description: "Generated by hyeju",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              {" "}
              <Link href="/about">/about</Link>{" "}
            </li>
            <li>
              {" "}
              <Link href="/blog">/blog</Link>{" "}
            </li>
          </ul>
        </nav>
        <input type="text" />
        {children}
      </body>
    </html>
  );
}
